<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Farmer Login</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h2>ðŸŒ¾Digital-Agro</h2>

    <form action="/login" method="post">
        <label>Username</label><br>
        <input type="text" name="username" required><br><br>

        <label>Password</label><br>
        <input type="password" name="password" required><br><br>

        <button type="submit">Login</button>
    </form>

    <p>New Farmer? <a href="register.html">Register here</a></p>
</body>
</html>
